//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuinCentrumMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        public int PlantNr { get; set; }
        public string Naam { get; set; }
        public int SoortNr { get; set; }
        public int Levnr { get; set; }
        public string Kleur { get; set; }
        public decimal VerkoopPrijs { get; set; }
    
        public virtual Leverancier Leverancier { get; set; }
        public virtual Soort Soort { get; set; }
    }
}
